config/routes.rb
Rails.application.routes.draw do

 

  get 'sessions/new'

resources :customers do
  member do
    get :followers,:following
  end
end

root 'static_pages#home'		

  get '/signup', to: 'customers#new'
  post '/signup', to: 'customers#create'

  get '/home', to: 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'
  get '/login' , to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create,:destroy]
  resources :relationships,only: [:create,:destroy]
  #patch '/customers/:id/edit', to: 'customers#update'

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(object.errors.count,"error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
	<li> <%=msg%></li>
	<% end %>
	</ul>
	</div>
	<% end%>

app/views/shared/_feed.html.erb
<%if @feed_items.any?%>
<ol class="microposts">
<%= render @feed_items %>
</ol>
<%=will_paginate @feed_items%>
<% end %>

app/views/shared/_follow_form.html.erb
	<% unless current_customer?(@customer)%>
	<div id="follow_form">
	<% if current_customer.following?(@customer)%>
		<%= render 'unfollow' %>
	<%else%>
	<%=	render 'follow' %>
	<% end %>
	</div>
	<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<%@customer ||= current_customer%>
<div class="stats">
<a href="<%=following_customer_path(@customer)%>">
<strong id="following" class="stat">
<%=@customer.following.count%>
</strong>
following
</a>

<a href="<%=followers_customer_path(@customer)%>">
<strong id="followers" class="stat">
<%=@customer.followers.count%>
</strong>
followers
</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_customer, size: 50), current_customer %>
<h1><%= current_customer.name %></h1>
<span><%= link_to "view my profile", current_customer %></span>
<span><%= pluralize(current_customer.microposts.count, "micropost") %></span>